name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - run: npm --version
      - run: node --version
      - run: cat package.json | grep typescript
      - run: cat package-lock.json | grep -A 5 -B 5 "typescript.*5\.9\.3"
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
